### ISSUE TITLE
Colorama missing

### ISSUE THREAD

**Issue by welldone43** [w-kuipers/python-project-minify#2]
Observation:
========
When running minify-project from the shell the terminal reports an error:

"File .../python3.11/site-packages/python_project_minify/python_project_minify.py", line 5, in <module>
    from colorama import init ..."

Interpretation:
=========
The package colorama is not listed as dependency of this project.

Work around
========
After installing colorama manually with "pip install colorama" the code did run as expedted.

**Comment by w-kuipers** [comment]
Thanks for the feedback! Fixed in [version 1.0.1](https://github.com/w-kuipers/python-project-minify/releases/tag/v1.0.1)
